python:
        build: ./python
        container_name: python-demo
        ports:
           - "5000:8080"
        links:
           - db


db:
        build: ./mysql-service
        container_name: db
        ports: 
           - "3306:3306"
        environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=domo_mom_db
           - MYSQL_USER=user1
           - MYSQL_PASSWORD=root

